config/routes.rb
Rails.application.routes.draw do
  resources :pending_toots
  resources :sticky_messages
  resources :other_files
  resources :video_files
  resources :audio_files
  resources :image_files
  resources :post_files
  resources :spam_comments
  get 'password_resets/new'

  get 'password_resets/edit'

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html
  

  # public views
  root   'main#timeline'
  get '/tml(/p/:page)', to: 'main#timeline', as: 'timeline'
  get '/mcrpst/:source/:id', to: 'main#micropost', as: 'micropost_view'
  get '/ctg/:id(/t/:tag)(/p/:page)', to: 'main#category', as: 'category'
  get '/blg(/p/:page)', to: 'main#blog', as: 'blog_view'
  get '/blg/:id', to: 'main#article', as: 'article'
  get '/prj/:id', to: 'main#project', as: 'page'
  get '/prjs', to: 'main#projects', as: 'pages'
  get '/media(/p/:page)', to: 'main#media', as: 'media'
  get '/prf/:id', to: 'main#profile', as: 'profile'
  get '/cms/:model/:id', to: 'comments#request_comments'
  get '/cms/form/:source_model/:source_id', to: 'comments#request_form',
    as: 'comment_form'
  get '/disclaimer(.:format)', to: 'main#disclaimer', as: 'disclaimer'
  get '/modal_text(.:format)', to: 'main#modal_text', as: 'modal_text'
  get '/blogfeed(.:format)', to: 'main#feed', as: 'rss_feed'
  get '/legal', to: 'main#legal', as: 'legal'
  get '/layout_switch', to: 'application#layout_switch', as: 'layout_switch'














  get    "/admin", to: 'admin_panel#index', as: 'admin'

  # account creation
  get 'sessions/new'
  get 'users/new'


  get    '/signup', to: 'users#new'
  #post   '/signup', to: 'users#create'

  get    '/login',  to: 'sessions#new', as: 'login_form'
  post   '/login',  to: 'sessions#create', as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  get      '/users/:id/edit_password', to: 'users#edit_password'
  patch    '/users/:id/edit_password', to: 'users#update_password'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  #namespace :admin do
  #  resources :requests
  #end
  resources :requests
  resources :comments
  resources :microposts
  resources :tags
  resources :blog_posts
  resources :blog_categories, only: [:index, :show]
  resources :projects
  resources :project_headers, only: [:index, :show]
  resources :social_media_links
  resources :ip_blacklists

  # special resource actions
  patch '/blog_posts/:id/hide', to: 'blog_posts#hide', as: 'hide_blog_post'
  patch '/blog_posts/:id/overwrite',
    to: 'blog_posts#overwrite_content', as: 'overwrite_blog_post'
  patch '/blog_posts/:id/publish',
    to: 'blog_posts#publish', as: 'publish_blog_post'

  patch '/projects/:id/hide', to: 'projects#hide', as: 'hide_project'
  patch '/projects/:id/overwrite', to: 'projects#overwrite_content',
    as: 'overwrite_project'
  patch '/projects/:id/publish',
    to: 'projects#publish', as: 'publish_project'

  get '/blog_posts/upload/draft_form',
    to: 'blog_posts#draft_upload_form', as: 'upload_form_blog_post'
  post '/blog_posts/upload/draft', to: 'blog_posts#draft_upload',
    as: 'upload_blog_post'

  patch '/blog_posts/:id/push_to_mstdn', to: 'blog_posts#push_to_mstdn',
    as: 'push_blog_post_to_mstdn'

  patch '/microposts/:id/push_to_mstdn', to: 'microposts#push_to_mstdn',
    as: 'push_micropost_to_mstdn'


  # error pages
  # get '404', :to => "main#error"
  
end

app/models/sticky_message.rb
class StickyMessage < ApplicationRecord
  belongs_to :user
end

app/controllers/sticky_messages_controller.rb
class StickyMessagesController < ApplicationController
  before_action :set_sticky_message, only: [:show, :edit, :update, :destroy]
  before_action :admin_user

  # GET /sticky_messages
  # GET /sticky_messages.json
  def index
    @sticky_messages = StickyMessage.all
  end

  # GET /sticky_messages/1
  # GET /sticky_messages/1.json
  def show
  end

  # GET /sticky_messages/new
  def new
    @sticky_message = StickyMessage.new
  end

  # GET /sticky_messages/1/edit
  def edit
  end

  # POST /sticky_messages
  # POST /sticky_messages.json
  def create
    @sticky_message = StickyMessage.new(sticky_message_params)
    @sticky_message.content = markup(@sticky_message.draft)
    @sticky_message.user_id = @current_user.id

    respond_to do |format|
      if @sticky_message.save
        format.html { redirect_to @sticky_message, notice: 'Sticky message was successfully created.' }
        format.json { render :show, status: :created, location: @sticky_message }
      else
        format.html { render :new }
        format.json { render json: @sticky_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sticky_messages/1
  # PATCH/PUT /sticky_messages/1.json
  def update
    @sticky_message.draft       = params[:sticky_message][:draft]
    @sticky_message.published   = params[:sticky_message][:published]
    @sticky_message.important   = params[:sticky_message][:important]
    @sticky_message.content     = markup(params[:sticky_message][:draft])
    respond_to do |format|
      if @sticky_message.save
        format.html { redirect_to @sticky_message, notice: 'Sticky message was successfully updated.' }
        format.json { render :show, status: :ok, location: @sticky_message }
      else
        format.html { render :edit }
        format.json { render json: @sticky_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sticky_messages/1
  # DELETE /sticky_messages/1.json
  def destroy
    @sticky_message.destroy
    respond_to do |format|
      format.html { redirect_to sticky_messages_url, notice: 'Sticky message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sticky_message
      @sticky_message = StickyMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sticky_message_params
      params.require(:sticky_message).permit(:draft, :published, :important)
    end
end

app/helpers/sticky_messages_helper.rb
module StickyMessagesHelper
end

app/views/sticky_messages/_form.html.erb
<%= form_with(model: sticky_message, local: true) do |form| %>
  <% if sticky_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sticky_message.errors.count, "error") %> prohibited this sticky_message from being saved:</h2>

      <ul>
      <% sticky_message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :draft %>
    <%= form.text_area :draft, id: :sticky_message_draft %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published, id: :sticky_message_published %>
  </div>

  <div class="field">
    <%= form.label :important %>
    <%= form.check_box :important, id: :sticky_message_important %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sticky_messages/edit.html.erb
<h1>Editing Sticky Message</h1>

<%= render 'form', sticky_message: @sticky_message %>

<%= link_to 'Show', @sticky_message %> |
<%= link_to 'Back', sticky_messages_path %>

app/views/sticky_messages/index.html.erb
<h1>Sticky Messages</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Draft</th>
      <th>Published</th>
      <th>Important</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sticky_messages.each do |sticky_message| %>
      <tr>
        <td><%= sticky_message.content %></td>
        <td><%= sticky_message.draft %></td>
        <td><%= sticky_message.published %></td>
        <td><%= sticky_message.important %></td>
        <td><%= sticky_message.user %></td>
        <td><%= link_to 'Show', sticky_message %></td>
        <td><%= link_to 'Edit', edit_sticky_message_path(sticky_message) %></td>
        <td><%= link_to 'Destroy', sticky_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sticky Message', new_sticky_message_path %>

app/views/sticky_messages/new.html.erb
<h1>New Sticky Message</h1>

<%= render 'form', sticky_message: @sticky_message %>

<%= link_to 'Back', sticky_messages_path %>

app/views/sticky_messages/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @sticky_message.content %>
</p>

<p>
  <strong>Draft:</strong>
  <%= @sticky_message.draft %>
</p>

<p>
  <strong>Published:</strong>
  <%= @sticky_message.published %>
</p>

<p>
  <strong>Important:</strong>
  <%= @sticky_message.important %>
</p>

<p>
  <strong>User:</strong>
  <%= @sticky_message.user %>
</p>

<%= link_to 'Edit', edit_sticky_message_path(@sticky_message) %> |
<%= link_to 'Back', sticky_messages_path %>