config/routes.rb
Rails.application.routes.draw do
  resources :pending_toots
  resources :sticky_messages
  resources :other_files
  resources :video_files
  resources :audio_files
  resources :image_files
  resources :post_files
  resources :spam_comments
  get 'password_resets/new'

  get 'password_resets/edit'

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html
  

  # public views
  root   'main#timeline'
  get '/tml(/p/:page)', to: 'main#timeline', as: 'timeline'
  get '/mcrpst/:source/:id', to: 'main#micropost', as: 'micropost_view'
  get '/ctg/:id(/t/:tag)(/p/:page)', to: 'main#category', as: 'category'
  get '/blg(/p/:page)', to: 'main#blog', as: 'blog_view'
  get '/blg/:id', to: 'main#article', as: 'article'
  get '/prj/:id', to: 'main#project', as: 'page'
  get '/prjs', to: 'main#projects', as: 'pages'
  get '/media(/p/:page)', to: 'main#media', as: 'media'
  get '/prf/:id', to: 'main#profile', as: 'profile'
  get '/cms/:model/:id', to: 'comments#request_comments'
  get '/cms/form/:source_model/:source_id', to: 'comments#request_form',
    as: 'comment_form'
  get '/disclaimer(.:format)', to: 'main#disclaimer', as: 'disclaimer'
  get '/modal_text(.:format)', to: 'main#modal_text', as: 'modal_text'
  get '/blogfeed(.:format)', to: 'main#feed', as: 'rss_feed'
  get '/legal', to: 'main#legal', as: 'legal'
  get '/layout_switch', to: 'application#layout_switch', as: 'layout_switch'














  get    "/admin", to: 'admin_panel#index', as: 'admin'

  # account creation
  get 'sessions/new'
  get 'users/new'


  get    '/signup', to: 'users#new'
  #post   '/signup', to: 'users#create'

  get    '/login',  to: 'sessions#new', as: 'login_form'
  post   '/login',  to: 'sessions#create', as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  get      '/users/:id/edit_password', to: 'users#edit_password'
  patch    '/users/:id/edit_password', to: 'users#update_password'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  #namespace :admin do
  #  resources :requests
  #end
  resources :requests
  resources :comments
  resources :microposts
  resources :tags
  resources :blog_posts
  resources :blog_categories, only: [:index, :show]
  resources :projects
  resources :project_headers, only: [:index, :show]
  resources :social_media_links
  resources :ip_blacklists

  # special resource actions
  patch '/blog_posts/:id/hide', to: 'blog_posts#hide', as: 'hide_blog_post'
  patch '/blog_posts/:id/overwrite',
    to: 'blog_posts#overwrite_content', as: 'overwrite_blog_post'
  patch '/blog_posts/:id/publish',
    to: 'blog_posts#publish', as: 'publish_blog_post'

  patch '/projects/:id/hide', to: 'projects#hide', as: 'hide_project'
  patch '/projects/:id/overwrite', to: 'projects#overwrite_content',
    as: 'overwrite_project'
  patch '/projects/:id/publish',
    to: 'projects#publish', as: 'publish_project'

  get '/blog_posts/upload/draft_form',
    to: 'blog_posts#draft_upload_form', as: 'upload_form_blog_post'
  post '/blog_posts/upload/draft', to: 'blog_posts#draft_upload',
    as: 'upload_blog_post'

  patch '/blog_posts/:id/push_to_mstdn', to: 'blog_posts#push_to_mstdn',
    as: 'push_blog_post_to_mstdn'

  patch '/microposts/:id/push_to_mstdn', to: 'microposts#push_to_mstdn',
    as: 'push_micropost_to_mstdn'


  # error pages
  # get '404', :to => "main#error"
  
end

app/models/project.rb
class Project < ApplicationRecord
  attr_accessor :previous_header_id
  #belongs_to :project_draft

  after_destroy :clean_header
  #after_save :clean_image_dimensions

  #mount_uploaders :images, ProjectImageUploader
  mount_uploader  :icon,   ProjectIconUploader

  validates :name, presence: true, length: { maximum: 128 },
    uniqueness: { case_sensitive: false }
  validate :content_yaml_check

  #validate :image_size_validation
  validates_processing_of :icon
  validate :icon_size_validation

  #if Rails.env = "development"
    # workaround for json independent database
  #  serialize :images, JSON
  #  serialize :image_dimensions, JSON
  #end

  def clean_header_update
    if Project.where(project_header_id: self.previous_header_id).count == 0
      if header = ProjectHeader.find_by(id: self.previous_header_id)
        header.delete
      end
    end
  end 

  private

  def content_yaml_check
    #/\A---$(.+)^---/m =~ self.content
    /\A---(.+)---/m =~ self.draft
    if $~
      if $~.to_s.include? "!ruby"
        self.errors.add :draft, "Invalid YAML frontmatter"
      else
        data = YAML.load($~.to_s)
        if data.is_a?(Hash)
          if (data.has_key?("header")) == false ||
              data.size > 1
            self.errors.add :content, "Invalid YAML keys(invalid hash)"
          end
        else
            self.errors.add :content, "Invalid YAML keys(not a hash)"
        end

      end
    else
      self.errors.add :content, "Invalid YAML frontmatter"
    end
  end

    #def clean_image_dimensions
    #  if image_dimensions
    #    if images
    #      remove_c = image_dimensions.size - images.size
    #      if remove_c > 0
    #        self.image_dimensions = image_dimensions.drop(remove_c)
    #        self.save
    #      end
    #    else
    #      self.image_dimensions = nil
    #      self.save
    #    end
    #  end
    #end

    def clean_header
      if Project.where(project_header_id: self.project_header_id).count == 0
        if header = ProjectHeader.find_by(id: self.project_header_id)
          header.delete
        end
      end
    end 


    #def image_size_validation
    #  if images
    #    images.each do |img|
    #      if img.size > 1.megabytes
    #        errors.add(:images, "should be less than 500KB each")
    #      end
    #    end
    #  end
    #end

    def icon_size_validation
      if icon && icon.size > 0.3.megabytes
        errors.add(:icon, "should be less than 300KB")
      end
    end

  protected


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :publish,
                                     :overwrite_content]
  before_action :admin_user

  # GET /projects # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @header  = ProjectHeader.new
    if @project.draft.nil?
      @project.draft = "---\nheader: Default\n---"
    end
  end

  # GET /projects/1/edit
  def edit
    @header  = ProjectHeader.find_by(id: @project.project_header_id)
  end

  # POST /projects
  # POST /projects.json
  def create
    @project   = Project.new(project_params)
    @header    = ProjectHeader.new
    header_ok  = false
    project_ok = false
    if @project.save
      data = YAML.load(@project.draft)
      data.symbolize_keys!
      # process header
      unless @header = ProjectHeader.find_by(name: data[:header])
        @header = ProjectHeader.create(name: data[:header])
        unless @header.errors.any?
          header_new = true
          header_ok = true
        else
          header_new = false
          header_ok = false
        end
      else
        header_ok = true
      end
      # process project
      content = @project.draft.split("---\r\n")
      if content[2]
        content_markup = markup(content[2])
        @project.update(project_header_id: @header.id, content: content_markup,
                        published: false)
        project_ok =  !@project.errors.any?
      else
        @project.errors.add :draft, "no content submitted"
      end
    end
    if header_ok && project_ok

      redirect_to @project,
        notice: 'Project was successfully created.'
    else
      if header_new
        @header.delete
      end
      @project.delete
      render :new 
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    @header    = ProjectHeader.new
    @project.previous_header_id = @project.project_header_id
    header_ok  = false
    project_ok = false
    @project.update(project_params)
    unless @project.errors.any?
      data = YAML.load(@project.draft)
      data.symbolize_keys!
      # process header
      unless @header = ProjectHeader.find_by(name: data[:header])
        @header = ProjectHeader.create(name: data[:header])
        unless @header.errors.any?
          header_new = true
          header_ok = true
        else
          header_new = false
          header_ok = false
        end
      else
        header_ok = true
      end
      # process project
      content = @project.draft.split("---\r\n")
      if content[2]
        content_markup = markup(content[2])
        @project.update(project_header_id: @header.id,)
        if @project.content != content_markup ||
           @project.content_update.present?

          @project.update(content_update: content_markup)
        end
        project_ok =  !@project.errors.any?
      else
        @project.errors.add :draft, "no content submitted"
      end
    end
    if header_ok && project_ok

      @project.clean_header_update

      redirect_to @project,
        notice: 'Project was successfully updated.'
    else
      if header_new
        @header.delete
      end
      render :edit
    end
  end

  def publish
    @project.update(published: true)
    redirect_to @project, notice: 'Project was successfully published'
  end
  
  def hide
    @project.update(published: false)
    redirect_to @project, notice: 'Project was successfully hidden'
  end

  def overwrite_content
    @project.content = @project.content_update
    @project.content_update = nil
    if @project.save
      redirect_to @project, notice: 'Content was replaced with updated value'
    else
      redirect_to @project, notice: 'Something went wrong'
    end
  end


  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :draft,
                                      :icon, :icon_cashe, :remove_icon)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? || @header.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count+@header.errors.count,
                        "error") %> prohibited this project from being 
                        saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      <% @header.errors.full_messages.each do |message| %>
        <li>(header) <%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name %>
  </div>
  
  <%= form.label :icon %>
  <%= image_tag(project.icon_url) if project.icon? %>
  <%= form.file_field :icon, class: 'form-control' %>
  <%= form.hidden_field :icon_cache %>
  <%= form.check_box :remove_icon %>
  <span>Remove icon</span>

  <div class="field">
    <%= form.label :draft %>
    <%= form.text_area :draft, id: :project_draft %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Update Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Header ID</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.project_header_id %></td>
        <td><%= project.published %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td>
          <%= link_to 'Destroy', project, 
            method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if project.published? %>
          <td><%= link_to 'Hide', hide_project_path(project),
            method: :patch, data: 
            { confirm: 'Are you sure to hide this project?' } %></td>
        <% else %>
          <td>
            <%= link_to 'Publish',
              publish_project_path(project), method: :patch,
              data:
              { confirm: 'Are you sure to publish this project?' }
            %>
          </td>
        <% end %>
        <% if project.content_update? %>
          <td><%= link_to 'Update', overwrite_project_path(project),
            method: :patch, data: 
            { confirm: 'Are you sure to update this project?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Header ID:</strong>
  <%= @project.project_header_id %>
</p>

<p>
  <strong>Published:</strong>
  <%= @project.published %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>