config/routes.rb
Rails.application.routes.draw do
  resources :pending_toots
  resources :sticky_messages
  resources :other_files
  resources :video_files
  resources :audio_files
  resources :image_files
  resources :post_files
  resources :spam_comments
  get 'password_resets/new'

  get 'password_resets/edit'

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html
  

  # public views
  root   'main#timeline'
  get '/tml(/p/:page)', to: 'main#timeline', as: 'timeline'
  get '/mcrpst/:source/:id', to: 'main#micropost', as: 'micropost_view'
  get '/ctg/:id(/t/:tag)(/p/:page)', to: 'main#category', as: 'category'
  get '/blg(/p/:page)', to: 'main#blog', as: 'blog_view'
  get '/blg/:id', to: 'main#article', as: 'article'
  get '/prj/:id', to: 'main#project', as: 'page'
  get '/prjs', to: 'main#projects', as: 'pages'
  get '/media(/p/:page)', to: 'main#media', as: 'media'
  get '/prf/:id', to: 'main#profile', as: 'profile'
  get '/cms/:model/:id', to: 'comments#request_comments'
  get '/cms/form/:source_model/:source_id', to: 'comments#request_form',
    as: 'comment_form'
  get '/disclaimer(.:format)', to: 'main#disclaimer', as: 'disclaimer'
  get '/modal_text(.:format)', to: 'main#modal_text', as: 'modal_text'
  get '/blogfeed(.:format)', to: 'main#feed', as: 'rss_feed'
  get '/legal', to: 'main#legal', as: 'legal'
  get '/layout_switch', to: 'application#layout_switch', as: 'layout_switch'














  get    "/admin", to: 'admin_panel#index', as: 'admin'

  # account creation
  get 'sessions/new'
  get 'users/new'


  get    '/signup', to: 'users#new'
  #post   '/signup', to: 'users#create'

  get    '/login',  to: 'sessions#new', as: 'login_form'
  post   '/login',  to: 'sessions#create', as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  get      '/users/:id/edit_password', to: 'users#edit_password'
  patch    '/users/:id/edit_password', to: 'users#update_password'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  #namespace :admin do
  #  resources :requests
  #end
  resources :requests
  resources :comments
  resources :microposts
  resources :tags
  resources :blog_posts
  resources :blog_categories, only: [:index, :show]
  resources :projects
  resources :project_headers, only: [:index, :show]
  resources :social_media_links
  resources :ip_blacklists

  # special resource actions
  patch '/blog_posts/:id/hide', to: 'blog_posts#hide', as: 'hide_blog_post'
  patch '/blog_posts/:id/overwrite',
    to: 'blog_posts#overwrite_content', as: 'overwrite_blog_post'
  patch '/blog_posts/:id/publish',
    to: 'blog_posts#publish', as: 'publish_blog_post'

  patch '/projects/:id/hide', to: 'projects#hide', as: 'hide_project'
  patch '/projects/:id/overwrite', to: 'projects#overwrite_content',
    as: 'overwrite_project'
  patch '/projects/:id/publish',
    to: 'projects#publish', as: 'publish_project'

  get '/blog_posts/upload/draft_form',
    to: 'blog_posts#draft_upload_form', as: 'upload_form_blog_post'
  post '/blog_posts/upload/draft', to: 'blog_posts#draft_upload',
    as: 'upload_blog_post'

  patch '/blog_posts/:id/push_to_mstdn', to: 'blog_posts#push_to_mstdn',
    as: 'push_blog_post_to_mstdn'

  patch '/microposts/:id/push_to_mstdn', to: 'microposts#push_to_mstdn',
    as: 'push_micropost_to_mstdn'


  # error pages
  # get '404', :to => "main#error"
  
end

app/models/spam_comment.rb
class SpamComment < ApplicationRecord
end

app/controllers/spam_comments_controller.rb
class SpamCommentsController < ApplicationController
  before_action :set_spam_comment, only: [:show, :edit, :update, :destroy]
  before_action :admin_user

  # GET /spam_comments
  # GET /spam_comments.json
  def index
    @spam_comments = SpamComment.all
  end

  # GET /spam_comments/1
  # GET /spam_comments/1.json
  def show
  end

  # GET /spam_comments/new
  def new
    @spam_comment = SpamComment.new
  end

  # GET /spam_comments/1/edit
  def edit
  end

  # POST /spam_comments
  # POST /spam_comments.json
  def create
    @spam_comment = SpamComment.new(spam_comment_params)

    respond_to do |format|
      if @spam_comment.save
        format.html { redirect_to @spam_comment, notice: 'Spam comment was successfully created.' }
        format.json { render :show, status: :created, location: @spam_comment }
      else
        format.html { render :new }
        format.json { render json: @spam_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spam_comments/1
  # PATCH/PUT /spam_comments/1.json
  def update
    respond_to do |format|
      if @spam_comment.update(spam_comment_params)
        format.html { redirect_to @spam_comment, notice: 'Spam comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @spam_comment }
      else
        format.html { render :edit }
        format.json { render json: @spam_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spam_comments/1
  # DELETE /spam_comments/1.json
  def destroy
    @spam_comment.destroy
    respond_to do |format|
      format.html { redirect_to spam_comments_url, notice: 'Spam comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spam_comment
      @spam_comment = SpamComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spam_comment_params
      params.require(:spam_comment).permit(:name, :email, :website, :content, :blog_spam_result, :blog_spam_reason, :blog_spam_blocker, :blog_spam_version, :ip, :useragent)
    end
end

app/helpers/spam_comments_helper.rb
module SpamCommentsHelper
end

app/views/spam_comments/_form.html.erb
<%= form_with(model: spam_comment, local: true) do |form| %>
  <% if spam_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spam_comment.errors.count, "error") %> prohibited this spam_comment from being saved:</h2>

      <ul>
      <% spam_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :spam_comment_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :spam_comment_email %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website, id: :spam_comment_website %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :spam_comment_content %>
  </div>

  <div class="field">
    <%= form.label :blog_spam_result %>
    <%= form.text_field :blog_spam_result, id: :spam_comment_blog_spam_result %>
  </div>

  <div class="field">
    <%= form.label :blog_spam_reason %>
    <%= form.text_field :blog_spam_reason, id: :spam_comment_blog_spam_reason %>
  </div>

  <div class="field">
    <%= form.label :blog_spam_blocker %>
    <%= form.text_field :blog_spam_blocker, id: :spam_comment_blog_spam_blocker %>
  </div>

  <div class="field">
    <%= form.label :blog_spam_version %>
    <%= form.text_field :blog_spam_version, id: :spam_comment_blog_spam_version %>
  </div>

  <div class="field">
    <%= form.label :ip %>
    <%= form.text_field :ip, id: :spam_comment_ip %>
  </div>

  <div class="field">
    <%= form.label :useragent %>
    <%= form.text_field :useragent, id: :spam_comment_useragent %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spam_comments/edit.html.erb
<h1>Editing Spam Comment</h1>

<%= render 'form', spam_comment: @spam_comment %>

<%= link_to 'Show', @spam_comment %> |
<%= link_to 'Back', spam_comments_path %>

app/views/spam_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spam Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Website</th>
      <th>Content</th>
      <th>Blog spam result</th>
      <th>Blog spam reason</th>
      <th>Blog spam blocker</th>
      <th>Blog spam version</th>
      <th>Ip</th>
      <th>Useragent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spam_comments.each do |spam_comment| %>
      <tr>
        <td><%= spam_comment.name %></td>
        <td><%= spam_comment.email %></td>
        <td><%= spam_comment.website %></td>
        <td><%= spam_comment.content %></td>
        <td><%= spam_comment.blog_spam_result %></td>
        <td><%= spam_comment.blog_spam_reason %></td>
        <td><%= spam_comment.blog_spam_blocker %></td>
        <td><%= spam_comment.blog_spam_version %></td>
        <td><%= spam_comment.ip %></td>
        <td><%= spam_comment.useragent %></td>
        <td><%= link_to 'Show', spam_comment %></td>
        <td><%= link_to 'Edit', edit_spam_comment_path(spam_comment) %></td>
        <td><%= link_to 'Destroy', spam_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spam Comment', new_spam_comment_path %>

app/views/spam_comments/new.html.erb
<h1>New Spam Comment</h1>

<%= render 'form', spam_comment: @spam_comment %>

<%= link_to 'Back', spam_comments_path %>

app/views/spam_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @spam_comment.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @spam_comment.email %>
</p>

<p>
  <strong>Website:</strong>
  <%= @spam_comment.website %>
</p>

<p>
  <strong>Content:</strong>
  <%= @spam_comment.content %>
</p>

<p>
  <strong>Blog spam result:</strong>
  <%= @spam_comment.blog_spam_result %>
</p>

<p>
  <strong>Blog spam reason:</strong>
  <%= @spam_comment.blog_spam_reason %>
</p>

<p>
  <strong>Blog spam blocker:</strong>
  <%= @spam_comment.blog_spam_blocker %>
</p>

<p>
  <strong>Blog spam version:</strong>
  <%= @spam_comment.blog_spam_version %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @spam_comment.ip %>
</p>

<p>
  <strong>Useragent:</strong>
  <%= @spam_comment.useragent %>
</p>

<%= link_to 'Edit', edit_spam_comment_path(@spam_comment) %> |
<%= link_to 'Back', spam_comments_path %>