config/routes.rb
Rails.application.routes.draw do
  resources :pending_toots
  resources :sticky_messages
  resources :other_files
  resources :video_files
  resources :audio_files
  resources :image_files
  resources :post_files
  resources :spam_comments
  get 'password_resets/new'

  get 'password_resets/edit'

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html
  

  # public views
  root   'main#timeline'
  get '/tml(/p/:page)', to: 'main#timeline', as: 'timeline'
  get '/mcrpst/:source/:id', to: 'main#micropost', as: 'micropost_view'
  get '/ctg/:id(/t/:tag)(/p/:page)', to: 'main#category', as: 'category'
  get '/blg(/p/:page)', to: 'main#blog', as: 'blog_view'
  get '/blg/:id', to: 'main#article', as: 'article'
  get '/prj/:id', to: 'main#project', as: 'page'
  get '/prjs', to: 'main#projects', as: 'pages'
  get '/media(/p/:page)', to: 'main#media', as: 'media'
  get '/prf/:id', to: 'main#profile', as: 'profile'
  get '/cms/:model/:id', to: 'comments#request_comments'
  get '/cms/form/:source_model/:source_id', to: 'comments#request_form',
    as: 'comment_form'
  get '/disclaimer(.:format)', to: 'main#disclaimer', as: 'disclaimer'
  get '/modal_text(.:format)', to: 'main#modal_text', as: 'modal_text'
  get '/blogfeed(.:format)', to: 'main#feed', as: 'rss_feed'
  get '/legal', to: 'main#legal', as: 'legal'
  get '/layout_switch', to: 'application#layout_switch', as: 'layout_switch'














  get    "/admin", to: 'admin_panel#index', as: 'admin'

  # account creation
  get 'sessions/new'
  get 'users/new'


  get    '/signup', to: 'users#new'
  #post   '/signup', to: 'users#create'

  get    '/login',  to: 'sessions#new', as: 'login_form'
  post   '/login',  to: 'sessions#create', as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  get      '/users/:id/edit_password', to: 'users#edit_password'
  patch    '/users/:id/edit_password', to: 'users#update_password'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  #namespace :admin do
  #  resources :requests
  #end
  resources :requests
  resources :comments
  resources :microposts
  resources :tags
  resources :blog_posts
  resources :blog_categories, only: [:index, :show]
  resources :projects
  resources :project_headers, only: [:index, :show]
  resources :social_media_links
  resources :ip_blacklists

  # special resource actions
  patch '/blog_posts/:id/hide', to: 'blog_posts#hide', as: 'hide_blog_post'
  patch '/blog_posts/:id/overwrite',
    to: 'blog_posts#overwrite_content', as: 'overwrite_blog_post'
  patch '/blog_posts/:id/publish',
    to: 'blog_posts#publish', as: 'publish_blog_post'

  patch '/projects/:id/hide', to: 'projects#hide', as: 'hide_project'
  patch '/projects/:id/overwrite', to: 'projects#overwrite_content',
    as: 'overwrite_project'
  patch '/projects/:id/publish',
    to: 'projects#publish', as: 'publish_project'

  get '/blog_posts/upload/draft_form',
    to: 'blog_posts#draft_upload_form', as: 'upload_form_blog_post'
  post '/blog_posts/upload/draft', to: 'blog_posts#draft_upload',
    as: 'upload_blog_post'

  patch '/blog_posts/:id/push_to_mstdn', to: 'blog_posts#push_to_mstdn',
    as: 'push_blog_post_to_mstdn'

  patch '/microposts/:id/push_to_mstdn', to: 'microposts#push_to_mstdn',
    as: 'push_micropost_to_mstdn'


  # error pages
  # get '404', :to => "main#error"
  
end

app/models/post_file.rb
class PostFile < ApplicationRecord
  mount_uploader :item, FileUploader


  #if Rails.env = "development"
    # workaround for json independent database
    serialize :image_dimensions, JSON
  #end

  private

end

app/controllers/post_files_controller.rb
class PostFilesController < ApplicationController
  before_action :set_post_file, only: [:show, :edit, :update, :destroy]
  before_action :admin_user

  # GET /post_files
  # GET /post_files.json
  def index
    @post_files = PostFile.all
  end

  # GET /post_files/1
  # GET /post_files/1.json
  def show
  end

  # GET /post_files/new
  def new
    @post_file = PostFile.new
  end

  # GET /post_files/1/edit
  def edit
  end

  # POST /post_files
  # POST /post_files.json
  def create
    @post_file = PostFile.new(post_file_params)

    respond_to do |format|
      if @post_file.save
        format.html { redirect_to @post_file, notice: 'Post file was successfully created.' }
        format.json { render :show, status: :created, location: @post_file }
      else
        format.html { render :new }
        format.json { render json: @post_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_files/1
  # PATCH/PUT /post_files/1.json
  def update
    respond_to do |format|
      if @post_file.update(post_file_params)
        format.html { redirect_to @post_file, notice: 'Post file was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_file }
      else
        format.html { render :edit }
        format.json { render json: @post_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_files/1
  # DELETE /post_files/1.json
  def destroy
    @post_file.destroy
    respond_to do |format|
      format.html { redirect_to post_files_url, notice: 'Post file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_file
      @post_file = PostFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_file_params
      params.require(:post_file).permit(:name, :item, :type, :image_dimensions,
                                        :remove_item, :item_cache)
    end
end

app/helpers/post_files_helper.rb
module PostFilesHelper
end

app/views/post_files/_form.html.erb
<%= form_with(model: post_file, local: true) do |form| %>
  <%= render 'shared/error_messages', object: form.object %>

  <div class="field">
    <%= form.label :item %>
    <%= image_tag(post_file.item_url) if post_file.item? %>
    <%= form.file_field :item, class: 'form-control' %>
    <%= form.hidden_field :item_cache %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :post_file_type %>
  </div>

  <div class="field">
    <%= form.label :image_dimensions %>
    <%= form.text_field :image_dimensions, id: :post_file_image_dimensions %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/post_files/edit.html.erb
<h1>Editing Post File</h1>

<%= render 'form', post_file: @post_file %>

<%= link_to 'Show', @post_file %> |
<%= link_to 'Back', post_files_path %>

app/views/post_files/index.html.erb
<h1>Post Files</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Item</th>
      <th>Type</th>
      <th>Image dimensions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_files.each do |post_file| %>
      <tr>
        <td><%= post_file.name %></td>
        <td><%= post_file.item %></td>
        <td><%= post_file.type %></td>
        <td><%= post_file.image_dimensions %></td>
        <td><%= link_to 'Show', post_file %></td>
        <td><%= link_to 'Edit', edit_post_file_path(post_file) %></td>
        <td><%= link_to 'Destroy', post_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post File', new_post_file_path %>

app/views/post_files/new.html.erb
<h1>New Post File</h1>

<%= render 'form', post_file: @post_file %>

<%= link_to 'Back', post_files_path %>

app/views/post_files/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @post_file.name %>
</p>

<p>
  <strong>Item:</strong>
  <%= @post_file.item %>
</p>

<p>
  <strong>Type:</strong>
  <%= @post_file.type %>
</p>

<p>
  <strong>Image dimensions:</strong>
  <%= @post_file.image_dimensions %>
</p>

<%= link_to 'Edit', edit_post_file_path(@post_file) %> |
<%= link_to 'Back', post_files_path %>